### PR TITLE
OLS-873: Ensure operator configures required OCP and Kubernetes version

### PR DESCRIPTION
**Pull request by syedriko**
## Description

Ensure operator configures required OCP and Kubernetes version

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes # https://issues.redhat.com/browse/OLS-873

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by raptorsun** [comment]
to add these configs, shall we use some special argument for `operator-sdk generate bundle` ?

**Comment by syedriko** [comment]
> to add these configs, shall we use some special argument for `operator-sdk generate bundle` ? if so, we may need update the Makefile so that we do not lose these new labels at next `make bundle`

What `make bundle` generates is far from what's checked in. I'm also not seeing how to feed what this PR adds to `generate bundle`.

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / bundle"
/override "Red Hat Konflux / ols-e2e-tests-rosa / bundle"

**Pull request merged**
