### PR TITLE
OLS-1162: update bundle with images from snapshot ols-tgdk7

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

bunlde is updated with snapshot[ ols-tgdk7](https://console.redhat.com/application-pipeline/workspaces/crt-nshift-lightspeed/applications/ols/snapshots/ols-tgdk7)

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by xrajesh** [comment]
/hold 
We have latest PR #556

**Comment by raptorsun** [comment]
/close
replaced by #556

**Pull request closed without merging**
