### PR TITLE
[OLS-1092] added APIVersion part of CRD

### PR DESCRIPTION
**Pull request by xrajesh**
## Description

Added APIVersion support for Azure Open AI.  This allows user to specify the API version that need to be used for chat completion API.
https://issues.redhat.com/browse/OLS-1092

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-1092](https://issues.redhat.com//browse/OLS-1092)
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / bundle "
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-operator"
/override "Red Hat Konflux / ols-enterprise-contract / pr group xav/apiversion"
/override "Red Hat Konflux / ols-enterprise-contract / test-bundle"

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / bundle"

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-operator"

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / pr group xav/apiversion"

**Comment by xrajesh** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / test-bundle"

**Pull request merged**
