### PR TITLE
OLS-567: fix syntax error in update_bundle_catalog.sh

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

fix a syntax error bug when using `RELATED_IMAGE` variable when calling `update_bundle_catalog.sh`

## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue # [OLS-567](https://issues.redhat.com//browse/OLS-567)
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by syedriko** [comment]
@raptorsun let's use this opportunity to fix a few spelling mistakes:
INTIAL: https://github.com/openshift/lightspeed-operator/blob/80490f0e131a81ec19efe30da0d3aa5a55153610/hack/update_bundle_catalog.sh#L33, https://github.com/openshift/lightspeed-operator/blob/80490f0e131a81ec19efe30da0d3aa5a55153610/hack/update_bundle_catalog.sh#L97
artifcts: https://github.com/openshift/lightspeed-operator/blob/80490f0e131a81ec19efe30da0d3aa5a55153610/hack/update_bundle_catalog.sh#L59
assitant: https://github.com/openshift/lightspeed-operator/blob/80490f0e131a81ec19efe30da0d3aa5a55153610/hack/update_bundle_catalog.sh#L78, https://github.com/openshift/lightspeed-operator/blob/80490f0e131a81ec19efe30da0d3aa5a55153610/hack/update_bundle_catalog.sh#L80

**Comment by raptorsun** [comment]
@syedriko Thank you for the review. all spellings are corrected now :)

**Review by tisnik — COMMENTED** [review]
lgtm

**Pull request merged**
