### PR TITLE
upgrade dependencies after golang 1.22 upgrade

### PR DESCRIPTION
**Pull request by raptorsun**
## Description
we have already upgraded to golang 1.22. now we can upgrade dependencies:
- sigs.k8s.io/controller-runtime v0.19.3 
- k8s.io/api v0.31.3
- k8s.io/apimachinery v0.31.3
- k8s.io/client-go v0.31.3
- controller-runtime 0.16.5

This PR replaces:
- https://github.com/openshift/lightspeed-operator/pull/340
- https://github.com/openshift/lightspeed-operator/pull/406
- https://github.com/openshift/lightspeed-operator/pull/408
- https://github.com/openshift/lightspeed-operator/pull/409

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [x] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it looks ok

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-operator"

**Pull request merged**
