### PR TITLE
moving to quay Org openshift-lightspeed

### PR DESCRIPTION
**Pull request by xrajesh**
## Description
Updated container image reference from Org openshift to openshift-lightspeed

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by xrajesh** [comment]
/hold
Hold until pre-req PRs are ready .

**Comment by bparees** [comment]
/retest

@xrajesh i assume you just did a global search/replace?

the new location mirroring is setup so we should be good to go now

**Comment by xrajesh** [comment]
>i assume you just did a global search/replace?
Yes + checked the script. Once the api and console ui gets published , I want to do a quick test .

**Comment by bparees** [comment]
> Yes + checked the script. Once the api and console ui gets published , I want to do a quick test .

everything is mirrored to the new quay org at this point

**Pull request merged**
