### PR TITLE
Add support for fake llm provider in operator as well

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Description
Adding fake_provider as one of supported provider, which will be helpful for load testing.

## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Closes # https://issues.redhat.com/browse/OLS-687?filter=-1 
- 
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested and verified in local and CI tests went through.

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

@xrajesh @raptorsun seems straightforward to me, anything missing?

**Comment by xrajesh** [comment]
We need to update the bundle artifacts to keep CSV file ins sync @vishnuchalla . run `make update-bundle-catalog` and include the bundle artifacts.

**Pull request merged**
