### PR TITLE
OLS-567 update bundle version to 0.1.0

### PR DESCRIPTION
**Pull request by raptorsun**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue # [OLS-567](https://issues.redhat.com//browse/OLS-567)
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it looks correct

**Comment by raptorsun** [comment]
EC checks find a violation from RAG image
```
"name": "lightspeed-rag-content",
            "containerImage": "quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-rag-content@sha256:4b46fb88f34d3b76261df86da309790a29d834a83b6503f0ccf08de45ff49c3b",
            "source": {
                "git": {
                    "url": "https://github.com/openshift/lightspeed-rag-content",
                    "revision": "808644eaffb7967b42480c751666e3e2d8ad738e",
                    "context": "./",
                    "dockerfileUrl": "Containerfile"
                }
            },
            "violations": [
                {
                    "msg": "Base images information is missing",
                    "metadata": {
                        "code": "base_image_registries.base_image_info_found",
                        "collections": [
                            "minimal",
                            "redhat"
                        ],
                        "depends_on": [
                            "attestation_type.known_attestation_type"
                        ],
                        "description": "Verify the expected information was provided about which base images were used during the build process.The list of base images is a combination of two sources. One is extracted from the SLSA Provenance in the form of Tekton Task result called BASE_IMAGES_DIGESTS. The other comes from the components in the `formulation` attribute of any associated CycloneDX SBOMs. To exclude this rule add \"base_image_registries.base_image_info_found\" to the `exclude` section of the policy configuration.",
                        "solution": "Either a Tekton task must exist that emits a result named BASE_IMAGES_DIGESTS, or a CycloneDX SBOM must be associated with the image.",
                        "title": "Base images provided"
                    }
                },

```

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / bundle"
/override "Red Hat Konflux / ols-e2e-tests-rosa / bundle"

**Pull request merged**
