### PR TITLE
build: change image registry to registry.redhat.io

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

use the image registry `registry.redhat.io` to pass the EC check for allowed base image registries.

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it looks ok!

**Comment by raptorsun** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / bundle"
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-operator"
/override "Red Hat Konflux / ols-enterprise-contract / test-bundle"

**Pull request merged**
