### PR TITLE
OLS-367: change OLSConfig CRD to cluster scope.

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

Chagne the OLSConfig CRD to a cluster scoped CRD.

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by vbelouso — COMMENTED** [review]
/lgtm

**Comment by vishnuchalla** [comment]
except for rebase, /lgtm

**Comment by raptorsun** [comment]
PR rebased, ready to review @vbelouso  @xrajesh  :)

**Pull request merged**
